name: Update Badminton FlyTV
on:
  schedule:
    - cron: '0 */1 * * *' # Jalan otomatis setiap 1 jam
  workflow_dispatch:      # Tombol manual di tab Actions
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install & Run
        run: |
          pip install requests
          python huya_grabber.py
      - name: Update Repository
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "HuyaBot"
          git add live.m3u
          git commit -m "Update Link Badminton via FlyTV Proxy" || exit 0
          git push
